/** Stitch-inspired visual themes per game route */

export const GAME_THEMES = {
  'quiz-adventure': {
    id: 'quiz-adventure',
    label: 'Phiêu lưu Quiz',
    emoji: '🗺️',
    icon: 'map',
    tagline: 'Trả lời đúng để đi tiếp trên bản đồ!',
    accent: '#1cb0f6',
    accentDark: '#1899d6',
    secondary: '#58cc02',
    gradient: 'linear-gradient(165deg, #c8e6ff 0%, #fbf9f8 42%, #fff8e1 100%)',
    pattern: 'adventure',
  },
  'math-battle': {
    id: 'math-battle',
    label: 'Đấu Toán',
    emoji: '⚔️',
    icon: 'calculate',
    tagline: 'Đánh bại đối thủ bằng tốc độ và combo!',
    accent: '#ff6b35',
    accentDark: '#e85a2a',
    secondary: '#ffc800',
    gradient: 'linear-gradient(165deg, #ffe8dc 0%, #fff5f0 40%, #fff8e1 100%)',
    pattern: 'battle',
  },
  'word-match': {
    id: 'word-match',
    label: 'Ghép Từ',
    emoji: '🔤',
    icon: 'spellcheck',
    tagline: 'Ghép từ với nghĩa — càng nhanh càng nhiều điểm!',
    accent: '#8b5cf6',
    accentDark: '#7c3aed',
    secondary: '#ff319f',
    gradient: 'linear-gradient(165deg, #ede9fe 0%, #fdf4ff 45%, #fbf9f8 100%)',
    pattern: 'match',
  },
  'memory-card': {
    id: 'memory-card',
    label: 'Thẻ Nhớ',
    emoji: '🃏',
    icon: 'grid_view',
    tagline: 'Lật thẻ và tìm cặp giống nhau!',
    accent: '#f59e0b',
    accentDark: '#d97706',
    secondary: '#1cb0f6',
    gradient: 'linear-gradient(165deg, #fef3c7 0%, #fffbeb 42%, #f0f9ff 100%)',
    pattern: 'memory',
  },
  'choose-1-of-2': {
    id: 'choose-1-of-2',
    label: 'Chọn 1 trong 2',
    emoji: '🎯',
    icon: 'touch_app',
    tagline: 'Chọn đáp án đúng nhanh nhất!',
    accent: '#006590',
    accentDark: '#004883',
    secondary: '#f7e61a',
    gradient: 'linear-gradient(180deg, #e0f2fe 0%, #f8f9fa 48%, #fff8e1 100%)',
    pattern: 'classic',
  },
  'listen-and-select': {
    id: 'listen-and-select',
    label: 'Nghe & Chọn',
    emoji: '🎧',
    icon: 'hearing',
    tagline: 'Luyện nghe và chọn từ đúng!',
    accent: '#ec4899',
    accentDark: '#db2777',
    secondary: '#1cb0f6',
    gradient: 'linear-gradient(165deg, #fce7f3 0%, #fdf2f8 40%, #fbf9f8 100%)',
    pattern: 'listen',
  },
  'simple-matching': {
    id: 'simple-matching',
    label: 'Ghép đôi',
    emoji: '🧩',
    icon: 'extension',
    tagline: 'Ghép cặp nhanh tay!',
    accent: '#14b8a6',
    accentDark: '#0d9488',
    secondary: '#58cc02',
    gradient: 'linear-gradient(165deg, #ccfbf1 0%, #f0fdfa 45%, #fbf9f8 100%)',
    pattern: 'match',
  },
  'daily-mission': {
    id: 'daily-mission',
    label: 'Nhiệm vụ ngày',
    emoji: '🏅',
    icon: 'emoji_events',
    tagline: 'Hoàn thành thử thách ngắn để giữ streak!',
    accent: '#58cc02',
    accentDark: '#46a302',
    secondary: '#ffc800',
    gradient: 'linear-gradient(165deg, #dcfce7 0%, #f7fee7 45%, #fbf9f8 100%)',
    pattern: 'daily',
  },
  'quiz-runner-3d': {
    id: 'quiz-runner-3d',
    label: 'Quiz Runner 3D',
    emoji: '🚀',
    icon: 'view_in_ar',
    tagline: 'Chạy qua cổng đáp án đúng trong không gian 3D!',
    accent: '#1cb0f6',
    accentDark: '#0074b8',
    secondary: '#58cc02',
    gradient: 'linear-gradient(165deg, #bae6fd 0%, #f0f9ff 42%, #ecfccb 100%)',
    pattern: 'runner',
  },
  'math-treasure': {
    id: 'math-treasure',
    label: 'Kho báu Toán',
    emoji: '💎',
    icon: 'diamond',
    tagline: 'Mở rương bằng phép tính và suy luận đúng!',
    accent: '#0ea5e9',
    accentDark: '#0369a1',
    secondary: '#f59e0b',
    gradient: 'linear-gradient(165deg, #dbeafe 0%, #f0f9ff 45%, #fef3c7 100%)',
    pattern: 'treasure',
  },
  'spelling-sprint': {
    id: 'spelling-sprint',
    label: 'Sprint Tiếng Việt',
    emoji: '✏️',
    icon: 'edit_note',
    tagline: 'Vượt chướng ngại bằng chính tả, từ ngữ và câu!',
    accent: '#ef4444',
    accentDark: '#b91c1c',
    secondary: '#f97316',
    gradient: 'linear-gradient(165deg, #fee2e2 0%, #fff7ed 48%, #ffffff 100%)',
    pattern: 'sprint',
  },
  'science-lab': {
    id: 'science-lab',
    label: 'Phòng thí nghiệm',
    emoji: '🔬',
    icon: 'experiment',
    tagline: 'Khám phá tự nhiên, cơ thể, năng lượng và môi trường!',
    accent: '#10b981',
    accentDark: '#047857',
    secondary: '#22c55e',
    gradient: 'linear-gradient(165deg, #d1fae5 0%, #ecfdf5 45%, #e0f2fe 100%)',
    pattern: 'lab',
  },
  'history-map': {
    id: 'history-map',
    label: 'Bản đồ Việt Nam',
    emoji: '🧭',
    icon: 'travel_explore',
    tagline: 'Mở địa danh, nhân vật và câu chuyện Việt Nam!',
    accent: '#f97316',
    accentDark: '#c2410c',
    secondary: '#14b8a6',
    gradient: 'linear-gradient(165deg, #ffedd5 0%, #fff7ed 45%, #ccfbf1 100%)',
    pattern: 'map',
  },
  'english-quest': {
    id: 'english-quest',
    label: 'English Quest',
    emoji: '🌍',
    icon: 'language',
    tagline: 'Làm quen tiếng Anh bằng từ vựng và phản xạ ngắn!',
    accent: '#6366f1',
    accentDark: '#4338ca',
    secondary: '#06b6d4',
    gradient: 'linear-gradient(165deg, #e0e7ff 0%, #eef2ff 45%, #cffafe 100%)',
    pattern: 'english',
  },
}

export function getGameTheme(gameType) {
  return GAME_THEMES[gameType] || GAME_THEMES['quiz-adventure']
}

export const HUB_GAMES = Object.values(GAME_THEMES).map(t => ({
  ...t,
  href: t.id.startsWith('choose') || t.id.includes('listen') || t.id.includes('matching')
    ? `/game-${t.id}`
    : `/game-${t.id}`,
}))
